package com.royarn.goods.dao;

import com.royarn.goods.entity.Device;
import com.royarn.goods.entity.DeviceExample;
import java.util.List;
import java.util.UUID;
import org.apache.ibatis.annotations.Param;

public interface DeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 12:25:21 CST 2018
     */
    int countByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 12:25:21 CST 2018
     */
    int deleteByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 12:25:21 CST 2018
     */
    int deleteByPrimaryKey(UUID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 12:25:21 CST 2018
     */
    int insert(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 12:25:21 CST 2018
     */
    int insertSelective(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 12:25:21 CST 2018
     */
    List<Device> selectByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 12:25:21 CST 2018
     */
    Device selectByPrimaryKey(UUID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 12:25:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") Device record, @Param("example") DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 12:25:21 CST 2018
     */
    int updateByExample(@Param("record") Device record, @Param("example") DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 12:25:21 CST 2018
     */
    int updateByPrimaryKeySelective(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 12:25:21 CST 2018
     */
    int updateByPrimaryKey(Device record);
}