package com.royarn.goods.dao;

import com.royarn.api.entity.Good;
import com.royarn.goods.entity.GoodExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    int countByExample(GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    int deleteByExample(GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    int insert(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    int insertSelective(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    List<Good> selectByExample(GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    Good selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") Good record, @Param("example") GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    int updateByExample(@Param("record") Good record, @Param("example") GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    int updateByPrimaryKeySelective(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    int updateByPrimaryKey(Good record);

    int batchInsert(@Param("goods") List<Good> goods);
}