package com.royarn.goods.dao;

import com.royarn.api.entity.Shop;
import com.royarn.goods.entity.ShopExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    int countByExample(ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    int deleteByExample(ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    int insert(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    int insertSelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    List<Shop> selectByExample(ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    Shop selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") Shop record, @Param("example") ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    int updateByExample(@Param("record") Shop record, @Param("example") ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    int updateByPrimaryKeySelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop
     *
     * @mbggenerated Tue Oct 30 15:18:51 CST 2018
     */
    int updateByPrimaryKey(Shop record);

    int batchInsert(@Param("shops") List<Shop> shops);
}