package com.royarn.goods.entity;

public class Camera {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.camera_no
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String cameraNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.name
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.pin_yin
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String pinYin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.pin_yin_ad
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String pinYinAd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.level
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.cid
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.node_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String nodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.group_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.device_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.device_type
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Byte deviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.chan_no
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String chanNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.chan_param
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String chanParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.gb_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String gbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.gb_id_map
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String gbIdMap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.dpi
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String dpi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.ptz
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String ptz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.longitude
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.latitude
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.merge
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String merge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.type
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.status
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.relation_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String relationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.from_group_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String fromGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.from_merge
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String fromMerge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.transport
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String transport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.sort
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Long sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.path
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.manufacturer
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String manufacturer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.model
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.owner
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.block
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String block;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.address
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.parental
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Integer parental;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.safetyway
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Integer safetyway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.secrecy
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Integer secrecy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.position
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Integer position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.room
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Integer room;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.uses
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Integer uses;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.supplylight
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Integer supplylight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.direction
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Integer direction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.stream_number
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Integer streamNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.analog_type
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Integer analogType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.mac
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String mac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.version
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.is_local
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Byte isLocal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.chan_sort
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String chanSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.record_key
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String recordKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.video_flow_type
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Byte videoFlowType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.flow_platform_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String flowPlatformId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.voice_talk_channel_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String voiceTalkChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.audit_status
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Integer auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.angle
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Double angle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.radius
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Double radius;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.SXJZXZT
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String sxjzxzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.is_video_plan
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private Integer isVideoPlan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.ext
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String ext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_camera.audit_record
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    private String auditRecord;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.id
     *
     * @return the value of dev_device_camera.id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.id
     *
     * @param id the value for dev_device_camera.id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.camera_no
     *
     * @return the value of dev_device_camera.camera_no
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getCameraNo() {
        return cameraNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.camera_no
     *
     * @param cameraNo the value for dev_device_camera.camera_no
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setCameraNo(String cameraNo) {
        this.cameraNo = cameraNo == null ? null : cameraNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.name
     *
     * @return the value of dev_device_camera.name
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.name
     *
     * @param name the value for dev_device_camera.name
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.pin_yin
     *
     * @return the value of dev_device_camera.pin_yin
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getPinYin() {
        return pinYin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.pin_yin
     *
     * @param pinYin the value for dev_device_camera.pin_yin
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setPinYin(String pinYin) {
        this.pinYin = pinYin == null ? null : pinYin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.pin_yin_ad
     *
     * @return the value of dev_device_camera.pin_yin_ad
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getPinYinAd() {
        return pinYinAd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.pin_yin_ad
     *
     * @param pinYinAd the value for dev_device_camera.pin_yin_ad
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setPinYinAd(String pinYinAd) {
        this.pinYinAd = pinYinAd == null ? null : pinYinAd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.level
     *
     * @return the value of dev_device_camera.level
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.level
     *
     * @param level the value for dev_device_camera.level
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.cid
     *
     * @return the value of dev_device_camera.cid
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.cid
     *
     * @param cid the value for dev_device_camera.cid
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.node_id
     *
     * @return the value of dev_device_camera.node_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.node_id
     *
     * @param nodeId the value for dev_device_camera.node_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId == null ? null : nodeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.group_id
     *
     * @return the value of dev_device_camera.group_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.group_id
     *
     * @param groupId the value for dev_device_camera.group_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.device_id
     *
     * @return the value of dev_device_camera.device_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.device_id
     *
     * @param deviceId the value for dev_device_camera.device_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.device_type
     *
     * @return the value of dev_device_camera.device_type
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Byte getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.device_type
     *
     * @param deviceType the value for dev_device_camera.device_type
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setDeviceType(Byte deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.chan_no
     *
     * @return the value of dev_device_camera.chan_no
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getChanNo() {
        return chanNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.chan_no
     *
     * @param chanNo the value for dev_device_camera.chan_no
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setChanNo(String chanNo) {
        this.chanNo = chanNo == null ? null : chanNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.chan_param
     *
     * @return the value of dev_device_camera.chan_param
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getChanParam() {
        return chanParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.chan_param
     *
     * @param chanParam the value for dev_device_camera.chan_param
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setChanParam(String chanParam) {
        this.chanParam = chanParam == null ? null : chanParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.gb_id
     *
     * @return the value of dev_device_camera.gb_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getGbId() {
        return gbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.gb_id
     *
     * @param gbId the value for dev_device_camera.gb_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setGbId(String gbId) {
        this.gbId = gbId == null ? null : gbId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.gb_id_map
     *
     * @return the value of dev_device_camera.gb_id_map
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getGbIdMap() {
        return gbIdMap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.gb_id_map
     *
     * @param gbIdMap the value for dev_device_camera.gb_id_map
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setGbIdMap(String gbIdMap) {
        this.gbIdMap = gbIdMap == null ? null : gbIdMap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.dpi
     *
     * @return the value of dev_device_camera.dpi
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getDpi() {
        return dpi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.dpi
     *
     * @param dpi the value for dev_device_camera.dpi
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setDpi(String dpi) {
        this.dpi = dpi == null ? null : dpi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.ptz
     *
     * @return the value of dev_device_camera.ptz
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getPtz() {
        return ptz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.ptz
     *
     * @param ptz the value for dev_device_camera.ptz
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setPtz(String ptz) {
        this.ptz = ptz == null ? null : ptz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.longitude
     *
     * @return the value of dev_device_camera.longitude
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.longitude
     *
     * @param longitude the value for dev_device_camera.longitude
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.latitude
     *
     * @return the value of dev_device_camera.latitude
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.latitude
     *
     * @param latitude the value for dev_device_camera.latitude
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.merge
     *
     * @return the value of dev_device_camera.merge
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getMerge() {
        return merge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.merge
     *
     * @param merge the value for dev_device_camera.merge
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setMerge(String merge) {
        this.merge = merge == null ? null : merge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.type
     *
     * @return the value of dev_device_camera.type
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.type
     *
     * @param type the value for dev_device_camera.type
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.status
     *
     * @return the value of dev_device_camera.status
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.status
     *
     * @param status the value for dev_device_camera.status
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.relation_id
     *
     * @return the value of dev_device_camera.relation_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.relation_id
     *
     * @param relationId the value for dev_device_camera.relation_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setRelationId(String relationId) {
        this.relationId = relationId == null ? null : relationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.from_group_id
     *
     * @return the value of dev_device_camera.from_group_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getFromGroupId() {
        return fromGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.from_group_id
     *
     * @param fromGroupId the value for dev_device_camera.from_group_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setFromGroupId(String fromGroupId) {
        this.fromGroupId = fromGroupId == null ? null : fromGroupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.from_merge
     *
     * @return the value of dev_device_camera.from_merge
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getFromMerge() {
        return fromMerge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.from_merge
     *
     * @param fromMerge the value for dev_device_camera.from_merge
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setFromMerge(String fromMerge) {
        this.fromMerge = fromMerge == null ? null : fromMerge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.transport
     *
     * @return the value of dev_device_camera.transport
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getTransport() {
        return transport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.transport
     *
     * @param transport the value for dev_device_camera.transport
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setTransport(String transport) {
        this.transport = transport == null ? null : transport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.sort
     *
     * @return the value of dev_device_camera.sort
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.sort
     *
     * @param sort the value for dev_device_camera.sort
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.path
     *
     * @return the value of dev_device_camera.path
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.path
     *
     * @param path the value for dev_device_camera.path
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.manufacturer
     *
     * @return the value of dev_device_camera.manufacturer
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.manufacturer
     *
     * @param manufacturer the value for dev_device_camera.manufacturer
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.model
     *
     * @return the value of dev_device_camera.model
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.model
     *
     * @param model the value for dev_device_camera.model
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.owner
     *
     * @return the value of dev_device_camera.owner
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.owner
     *
     * @param owner the value for dev_device_camera.owner
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.block
     *
     * @return the value of dev_device_camera.block
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getBlock() {
        return block;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.block
     *
     * @param block the value for dev_device_camera.block
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setBlock(String block) {
        this.block = block == null ? null : block.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.address
     *
     * @return the value of dev_device_camera.address
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.address
     *
     * @param address the value for dev_device_camera.address
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.parental
     *
     * @return the value of dev_device_camera.parental
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Integer getParental() {
        return parental;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.parental
     *
     * @param parental the value for dev_device_camera.parental
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setParental(Integer parental) {
        this.parental = parental;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.safetyway
     *
     * @return the value of dev_device_camera.safetyway
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Integer getSafetyway() {
        return safetyway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.safetyway
     *
     * @param safetyway the value for dev_device_camera.safetyway
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setSafetyway(Integer safetyway) {
        this.safetyway = safetyway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.secrecy
     *
     * @return the value of dev_device_camera.secrecy
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Integer getSecrecy() {
        return secrecy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.secrecy
     *
     * @param secrecy the value for dev_device_camera.secrecy
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setSecrecy(Integer secrecy) {
        this.secrecy = secrecy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.position
     *
     * @return the value of dev_device_camera.position
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.position
     *
     * @param position the value for dev_device_camera.position
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.room
     *
     * @return the value of dev_device_camera.room
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Integer getRoom() {
        return room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.room
     *
     * @param room the value for dev_device_camera.room
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setRoom(Integer room) {
        this.room = room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.uses
     *
     * @return the value of dev_device_camera.uses
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Integer getUses() {
        return uses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.uses
     *
     * @param uses the value for dev_device_camera.uses
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setUses(Integer uses) {
        this.uses = uses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.supplylight
     *
     * @return the value of dev_device_camera.supplylight
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Integer getSupplylight() {
        return supplylight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.supplylight
     *
     * @param supplylight the value for dev_device_camera.supplylight
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setSupplylight(Integer supplylight) {
        this.supplylight = supplylight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.direction
     *
     * @return the value of dev_device_camera.direction
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Integer getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.direction
     *
     * @param direction the value for dev_device_camera.direction
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setDirection(Integer direction) {
        this.direction = direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.stream_number
     *
     * @return the value of dev_device_camera.stream_number
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Integer getStreamNumber() {
        return streamNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.stream_number
     *
     * @param streamNumber the value for dev_device_camera.stream_number
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setStreamNumber(Integer streamNumber) {
        this.streamNumber = streamNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.analog_type
     *
     * @return the value of dev_device_camera.analog_type
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Integer getAnalogType() {
        return analogType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.analog_type
     *
     * @param analogType the value for dev_device_camera.analog_type
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setAnalogType(Integer analogType) {
        this.analogType = analogType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.mac
     *
     * @return the value of dev_device_camera.mac
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.mac
     *
     * @param mac the value for dev_device_camera.mac
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setMac(String mac) {
        this.mac = mac == null ? null : mac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.version
     *
     * @return the value of dev_device_camera.version
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.version
     *
     * @param version the value for dev_device_camera.version
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.is_local
     *
     * @return the value of dev_device_camera.is_local
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Byte getIsLocal() {
        return isLocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.is_local
     *
     * @param isLocal the value for dev_device_camera.is_local
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setIsLocal(Byte isLocal) {
        this.isLocal = isLocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.chan_sort
     *
     * @return the value of dev_device_camera.chan_sort
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getChanSort() {
        return chanSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.chan_sort
     *
     * @param chanSort the value for dev_device_camera.chan_sort
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setChanSort(String chanSort) {
        this.chanSort = chanSort == null ? null : chanSort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.record_key
     *
     * @return the value of dev_device_camera.record_key
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getRecordKey() {
        return recordKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.record_key
     *
     * @param recordKey the value for dev_device_camera.record_key
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setRecordKey(String recordKey) {
        this.recordKey = recordKey == null ? null : recordKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.video_flow_type
     *
     * @return the value of dev_device_camera.video_flow_type
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Byte getVideoFlowType() {
        return videoFlowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.video_flow_type
     *
     * @param videoFlowType the value for dev_device_camera.video_flow_type
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setVideoFlowType(Byte videoFlowType) {
        this.videoFlowType = videoFlowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.flow_platform_id
     *
     * @return the value of dev_device_camera.flow_platform_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getFlowPlatformId() {
        return flowPlatformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.flow_platform_id
     *
     * @param flowPlatformId the value for dev_device_camera.flow_platform_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setFlowPlatformId(String flowPlatformId) {
        this.flowPlatformId = flowPlatformId == null ? null : flowPlatformId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.voice_talk_channel_id
     *
     * @return the value of dev_device_camera.voice_talk_channel_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getVoiceTalkChannelId() {
        return voiceTalkChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.voice_talk_channel_id
     *
     * @param voiceTalkChannelId the value for dev_device_camera.voice_talk_channel_id
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setVoiceTalkChannelId(String voiceTalkChannelId) {
        this.voiceTalkChannelId = voiceTalkChannelId == null ? null : voiceTalkChannelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.audit_status
     *
     * @return the value of dev_device_camera.audit_status
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.audit_status
     *
     * @param auditStatus the value for dev_device_camera.audit_status
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.angle
     *
     * @return the value of dev_device_camera.angle
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Double getAngle() {
        return angle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.angle
     *
     * @param angle the value for dev_device_camera.angle
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setAngle(Double angle) {
        this.angle = angle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.radius
     *
     * @return the value of dev_device_camera.radius
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Double getRadius() {
        return radius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.radius
     *
     * @param radius the value for dev_device_camera.radius
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setRadius(Double radius) {
        this.radius = radius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.SXJZXZT
     *
     * @return the value of dev_device_camera.SXJZXZT
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getSxjzxzt() {
        return sxjzxzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.SXJZXZT
     *
     * @param sxjzxzt the value for dev_device_camera.SXJZXZT
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setSxjzxzt(String sxjzxzt) {
        this.sxjzxzt = sxjzxzt == null ? null : sxjzxzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.is_video_plan
     *
     * @return the value of dev_device_camera.is_video_plan
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public Integer getIsVideoPlan() {
        return isVideoPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.is_video_plan
     *
     * @param isVideoPlan the value for dev_device_camera.is_video_plan
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setIsVideoPlan(Integer isVideoPlan) {
        this.isVideoPlan = isVideoPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.ext
     *
     * @return the value of dev_device_camera.ext
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getExt() {
        return ext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.ext
     *
     * @param ext the value for dev_device_camera.ext
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setExt(String ext) {
        this.ext = ext == null ? null : ext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_camera.audit_record
     *
     * @return the value of dev_device_camera.audit_record
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public String getAuditRecord() {
        return auditRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_camera.audit_record
     *
     * @param auditRecord the value for dev_device_camera.audit_record
     *
     * @mbggenerated Tue Feb 19 14:59:51 CST 2019
     */
    public void setAuditRecord(String auditRecord) {
        this.auditRecord = auditRecord == null ? null : auditRecord.trim();
    }
}